// export const SUCCESSFUL_LOADED_POSTS = 'SUCCESSFUL_LOADED_POSTS';
// export const FAILED_LOADED_POSTS = 'FAILED_LOADED_POSTS';
//
export const ADD_POST_UNSUCCESSFUL = 'ADD_POST_UNSUCCESSFUL';
export const ADD_POST_SUCCESSFUL = 'ADD_POST_UNSUCCESSFUL';
//
// export const UNADDED_POST = 'UNADDED_POST';

export const GET_POSTS = 'GET_POSTS';
// export const ADD_POST_UNSUCCESSFUL = 'ADD_POST_UNSUCCESSFUL';
export const UNADDED_POST = 'UNADDED_POST';